# Generated by Django 5.0.6 on 2024-05-30 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank='True', null='True', upload_to='media/photo', verbose_name='Превью'),
        ),
    ]
