# Generated by Django 5.0.6 on 2024-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_at_alter_blog_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank='True', null='True', upload_to='blog/photo', verbose_name='Превью'),
        ),
    ]
