# Generated by Django 5.0.6 on 2024-05-20 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Введите телефон', max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, help_text='Введите сообщение', null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дату создания', verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Не указан', help_text='Введите адрес', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='inn',
            field=models.CharField(default='Не указан', help_text='Введите ИНН', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Введите название подразделения или укажите контактное лицо', max_length=50, verbose_name='Название/Имя'),
        ),
    ]
