# Generated by Django 5.0.6 on 2024-05-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_remove_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', help_text='Введите адрес', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.CharField(default='', help_text='Введите ИНН', max_length=12, verbose_name='ИНН'),
        ),
    ]
